using System;
using System.Collections;
using System.ComponentModel;
using System.Diagnostics;
using System.Drawing;
using System.Globalization;
using System.IO;
using System.Reflection;
using System.Resources;
using System.Runtime.InteropServices;
using System.Text;
using Microsoft.BizTalk.Component.Interop;
using Microsoft.BizTalk.Message.Interop;
using Modhul.BizTalk.PipelineComponents.CreateMessageBodyPart.EventLog;
using Modhul.BizTalk.PipelineComponents.CreateMessageBodyPart.Factories;
using IComponent=Microsoft.BizTalk.Component.Interop.IComponent;

namespace Modhul.BizTalk.PipelineComponents.CreateMessageBodyPart
{
    [ComponentCategory(CategoryTypes.CATID_PipelineComponent)]
    [Guid("eb908a14-8568-40a8-a32b-4c7f8c02368e")]
    [ComponentCategory(CategoryTypes.CATID_Decoder)]
    public class CreateMessageBodyPartComp : IComponent, IBaseComponent, IPersistPropertyBag, IComponentUI
    {
        /// <summary>
        /// Source of Event Log entries generated by this pipeline component.
        /// </summary>
        public const string EVENT_LOG_SOURCE = "BizTalk Create Message Body Part Component";

        private readonly ResourceManager resourceManager =
            new ResourceManager("Modhul.BizTalk.PipelineComponents.CreateMessageBodyPart.CreateMessageBodyPartComp",
                                Assembly.GetExecutingAssembly());

        private string bodyPartContent;
        private string bodyPartName;

        public string BodyPartContent
        {
            get { return bodyPartContent; }
            set { bodyPartContent = value; }
        }

        public string BodyPartName
        {
            get { return bodyPartName; }
            set { bodyPartName = value; }
        }

        #region IBaseComponent members

        /// <summary>
        /// Name of the component
        /// </summary>
        [Browsable(false)]
        public string Name
        {
            get { return resourceManager.GetString("COMPONENTNAME", CultureInfo.InvariantCulture); }
        }

        /// <summary>
        /// Version of the component
        /// </summary>
        [Browsable(false)]
        public string Version
        {
            get { return resourceManager.GetString("COMPONENTVERSION", CultureInfo.InvariantCulture); }
        }

        /// <summary>
        /// Description of the component
        /// </summary>
        [Browsable(false)]
        public string Description
        {
            get { return resourceManager.GetString("COMPONENTDESCRIPTION", CultureInfo.InvariantCulture); }
        }

        #endregion

        #region IPersistPropertyBag members

        /// <summary>
        /// Gets class ID of component for usage from unmanaged code.
        /// </summary>
        /// <param name="classid">
        /// Class ID of the component
        /// </param>
        public void GetClassID(out Guid classid)
        {
            classid = new Guid("eb908a14-8568-40a8-a32b-4c7f8c02368e");
        }

        /// <summary>
        /// not implemented
        /// </summary>
        public void InitNew()
        {
        }

        /// <summary>
        /// Loads configuration properties for the component
        /// </summary>
        /// <param name="pb">Configuration property bag</param>
        /// <param name="errlog">Error status</param>
        public virtual void Load(IPropertyBag pb, int errlog)
        {
            object val = null;
            val = ReadPropertyBag(pb, "BodyPartContent");
            if ((val != null))
            {
                bodyPartContent = ((string) (val));
            }
            val = ReadPropertyBag(pb, "BodyPartName");
            if ((val != null))
            {
                bodyPartName = ((string) (val));
            }
        }

        /// <summary>
        /// Saves the current component configuration into the property bag
        /// </summary>
        /// <param name="pb">Configuration property bag</param>
        /// <param name="fClearDirty">not used</param>
        /// <param name="fSaveAllProperties">not used</param>
        public virtual void Save(IPropertyBag pb, bool fClearDirty, bool fSaveAllProperties)
        {
            WritePropertyBag(pb, "BodyPartContent", BodyPartContent);
            WritePropertyBag(pb, "BodyPartName", BodyPartName);
        }

        #region utility functionality

        /// <summary>
        /// Reads property value from property bag
        /// </summary>
        /// <param name="pb">Property bag</param>
        /// <param name="propName">Name of property</param>
        /// <returns>Value of the property</returns>
        private object ReadPropertyBag(IPropertyBag pb, string propName)
        {
            object val = null;
            try
            {
                pb.Read(propName, out val, 0);
            }
            catch (ArgumentException)
            {
                return val;
            }
            catch (Exception e)
            {
                throw new ApplicationException(e.Message);
            }
            return val;
        }

        /// <summary>
        /// Writes property values into a property bag.
        /// </summary>
        /// <param name="pb">Property bag.</param>
        /// <param name="propName">Name of property.</param>
        /// <param name="val">Value of property.</param>
        private void WritePropertyBag(IPropertyBag pb, string propName, object val)
        {
            try
            {
                pb.Write(propName, ref val);
            }
            catch (Exception e)
            {
                throw new ApplicationException(e.Message);
            }
        }

        #endregion

        #endregion

        #region IComponentUI members

        /// <summary>
        /// Component icon to use in BizTalk Editor
        /// </summary>
        [Browsable(false)]
        public IntPtr Icon
        {
            get { return ((Bitmap) (resourceManager.GetObject("COMPONENTICON", CultureInfo.InvariantCulture))).GetHicon(); }
        }

        /// <summary>
        /// The Validate method is called by the BizTalk Editor during the build 
        /// of a BizTalk project.
        /// </summary>
        /// <param name="obj">An Object containing the configuration properties.</param>
        /// <returns>The IEnumerator enables the caller to enumerate through a collection of strings containing error messages. These error messages appear as compiler error messages. To report successful property validation, the method should return an empty enumerator.</returns>
        public IEnumerator Validate(object obj)
        {
            // example implementation:
            // ArrayList errorList = new ArrayList();
            // errorList.Add("This is a compiler error");
            // return errorList.GetEnumerator();
            return null;
        }

        #endregion

        #region IComponent members

        /// <summary>
        /// Implements IComponent.Execute method.
        /// </summary>
        /// <param name="context">Pipeline context</param>
        /// <param name="message">Input message</param>
        /// <returns>Original input message</returns>
        /// <remarks>
        /// IComponent.Execute method is used to initiate
        /// the processing of the message in this pipeline component.
        /// </remarks>
        public IBaseMessage Execute(IPipelineContext context, IBaseMessage message)
        {
            if (ComponentPropertiesAreValid())
            {
                if (MessageBodyPartIsNull(message))
                {
                    IBaseMessagePart messageBodyPart = CreateMessagePartFromBodyPartContentProperty();
                    message.AddPart(bodyPartName, messageBodyPart, true);
                    return (message);
                }
            }

            return (message);
        }

        #endregion

        #region Private Methods

        /// <summary>
        /// Checks that component properties are valid.
        /// </summary>
        /// <returns></returns>
        private bool ComponentPropertiesAreValid()
        {
            if (bodyPartName.Trim() == String.Empty)
            {
                System.Diagnostics.EventLog.WriteEntry(EVENT_LOG_SOURCE,
                                                       "The 'BodyPartName' component property is not correctly configured. The message will be passed to BizTalk, but a body part will not be created.",
                                                       EventLogEntryType.Error,
                                                       (int)
                                                       EventLogCategories.ComponentPropertyValidation.
                                                           BodyPartNamePropertyNotConfigured);
                return (false);
            }

            if (bodyPartContent.Trim() == String.Empty)
            {
                System.Diagnostics.EventLog.WriteEntry(EVENT_LOG_SOURCE,
                                                       "The 'BodyPartContent' component property is not correctly configured. The message will be passed to BizTalk, but a body part will not be created.",
                                                       EventLogEntryType.Error,
                                                       (int)
                                                       EventLogCategories.ComponentPropertyValidation.
                                                           BodyPartContentPropertyNotConfigured);
                return (false);
            }

            return (true);
        }

        private static bool MessageBodyPartIsNull(IBaseMessage message)
        {
            return (message.BodyPart == null);
        }

        /// <summary>
        /// Creates a new message part from string supplied in the 'BodyPartContent' component configuration 
        /// property.
        /// </summary>
        /// <returns></returns>
        private IBaseMessagePart CreateMessagePartFromBodyPartContentProperty()
        {
            IBaseMessagePart messagePart = MessagePartFactory.CreateMessagePart();
            messagePart.Data = CreateStreamFromString(bodyPartContent);
            messagePart.ContentType = "text/xml";
            messagePart.Charset = "utf-8";

            return (messagePart);
        }

        /// <summary>
        /// Creates a stream representation of the supplied string.
        /// </summary>
        /// <param name="content"></param>
        /// <returns></returns>
        private static Stream CreateStreamFromString(string content)
        {
            byte[] contentByteArray = Encoding.Unicode.GetBytes(content);
            return (new MemoryStream(contentByteArray));
        }

        #endregion
    }
}